
import { NextRequest, NextResponse } from 'next/server';
import { createSupabaseServerClient } from '@/lib/supabase/server';
import { calculateShipping, DEFAULT_SHIPPING_OUTSIDE } from '@/lib/shipping';

export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const { shippingAddress, billingAddress, sameAsShipping, paymentMethod } = body;

        if (paymentMethod !== 'COD') {
            return NextResponse.json({ error: 'Invalid payment method for this endpoint' }, { status: 400 });
        }

        // 1. Get Authenticated User
        const supabase = await createSupabaseServerClient();
        const { data: { user } } = await supabase.auth.getUser();

        if (!user) {
            return NextResponse.json({ error: 'User not authenticated' }, { status: 401 });
        }

        // 2. Fetch Cart Items
        const { data: cartData, error: cartError } = await supabase
            .from('cart_items')
            .select(`
                *,
                product:products (
                    name,
                    price,
                    discount_price
                )
            `)
            .eq('user_id', user.id);

        if (cartError) {
            console.error('[COD Order] Cart fetch error:', cartError);
            return NextResponse.json({ error: 'Failed to fetch cart' }, { status: 500 });
        }

        if (!cartData || cartData.length === 0) {
            return NextResponse.json({ error: 'Cart is empty or not found' }, { status: 400 });
        }

        const cartItems = cartData;

        // 3. Calculate Totals
        let subtotal = 0;
        cartItems.forEach((item: any) => {
            const price = item.product.discount_price || item.product.price;
            subtotal += price * item.quantity;
        });

        // 4. Flat shipping by destination pincode (TN vs outside), rates editable in admin
        const deliveryPincode = shippingAddress.pincode;
        const shippingCost = deliveryPincode
            ? await calculateShipping(deliveryPincode)
            : DEFAULT_SHIPPING_OUTSIDE;
        const codCharges = 0;

        const totalAmount = subtotal + shippingCost + codCharges;

        // 5. Create Order in Supabase
        const { data: order, error: orderError } = await supabase
            .from('orders')
            .insert({
                user_id: user.id,
                total: totalAmount, // Schema uses 'total'
                subtotal: subtotal,
                status: 'pending',
                // payment_method: 'COD', // Removing potentially non-existent columns to be safe
                // payment_status: 'pending', 

                // Flattened Shipping Address
                shipping_name: shippingAddress.name,
                shipping_phone: shippingAddress.phone,
                shipping_address_line1: shippingAddress.address,
                shipping_city: shippingAddress.city,
                shipping_state: shippingAddress.state,
                shipping_pincode: shippingAddress.pincode,

                shipping_cost: shippingCost + codCharges,
            })
            .select()
            .single();

        if (orderError) {
            console.error('Supabase Order Creation Error:', orderError);
            throw new Error(`Failed to create order record: ${orderError.message}`);
        }

        // 6. Create Order Items in Supabase
        const orderItemsNodes = cartItems.map((item: any) => ({
            order_id: order.id,
            product_id: item.product_id,
            quantity: item.quantity,
            price: item.product.discount_price || item.product.price,
            size: item.size,
            color: item.color || null,
            combo_type: item.combo_type || 'single',
            baby_size: item.baby_size || null,
            product_name: item.product.name,
            unit_price: item.product.discount_price || item.product.price,
            total_price: (item.product.discount_price || item.product.price) * item.quantity,
        }));

        const { error: itemsError } = await supabase
            .from('order_items')
            .insert(orderItemsNodes);

        if (itemsError) {
            console.error('Supabase Order Items Error:', itemsError);
        }

        // 7. Clear Cart
        await supabase
            .from('cart_items')
            .delete()
            .eq('user_id', user.id);

        // Trigger push notification to admins
        try {
            const { sendAdminOrderNotification } = await import('@/lib/webpush');
            const productNames = orderItemsNodes.map((item: any) => `${item.product_name} x${item.quantity}`).join(', ');
            // The schema 'orders' has order_number generated by trigger, we'll try to fetch it or just use 'New Order'
            let orderNumStr = 'New Order';
            if (order.order_number) orderNumStr = order.order_number;
            await sendAdminOrderNotification(orderNumStr, totalAmount, productNames);
        } catch (pushErr) {
            console.error('[WebPush] Error triggering push:', pushErr);
        }

        return NextResponse.json({
            success: true,
            orderId: order.id,
            orderNumber: order.id
        });

    } catch (error: any) {
        console.error('COD Order Error:', error);
        return NextResponse.json({ error: error.message || 'Internal Server Error' }, { status: 500 });
    }
}
